# -----------------------------------------------------------------------------
# Configuration file for the nexgrc_client
# -----------------------------------------------------------------------------

# Connection  configuration - robot ip and port

robot_ip : "192.168.0.12"
robot_port : 1688
accept_joint_command : true
